name: build-and-deploy

on:
  schedule:
    - cron: '0 0 * * 5'
  # push:
  #   branches:
  #     - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v1
        env:
          TZ: Asia/Shanghai
        with:
          node-version: '12'
          registry-url: https://registry.npm.taobao.org/

      - name: build
        run: yarn && yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          publish_branch: master # default: gh-pages
